"""empty message

Revision ID: 2274f4b6f850
Revises: 85701cf8caae
Create Date: 2023-01-02 23:01:43.419804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2274f4b6f850'
down_revision = '85701cf8caae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
